pipeline {

    agent any
 
    
    tools {
       maven 'Maven-3.8.6' 
    }
    
    environment {
     	imagename = "venus90210/sorteo_api"
    	registryCredential = 'kevalnagda'
        DATE = new Date().format('yy.M')
        TAG = "${DATE}.${BUILD_NUMBER}"
    }
    

    
    stages { 
    
        stage('Source') {
            steps {

                git branch: 'develop', url: 'https://github.com/AAMAYAG-TFM/SORTEO_API.git'
            }
        }   
         
         stage ('Build') {
            
            steps {
                echo 'Construyendo proyecto'
 
                sh 'mvn -Dhttps.protocols=TLSv1.2 -f /var/lib/jenkins/workspace/sorteo/sorteo/pom.xml clean package'
            }
        }
        
        stage('Docker Build') {
            steps {
                echo 'Construyendo imagen'
                app = docker.build("sorteo_api")
                //sh 'docker build -t venus90210/sorteo_api:latest /sorteo/.'
            }
        }
          
        stage('Deploy') {
            steps {
                script{
                    docker.withRegistry('https://165669622759.dkr.ecr.us-east-1.amazonaws.com', 'ecr:us-east-1:aws-credentials') {
                    app.push("${env.BUILD_NUMBER}")
                    app.push("latest")
                    }
                }
            }
        }
        
        stage('Test') {
            steps {
                echo 'Hello world!' 
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Hello world!' 
            }
        }
    }
}