pipeline {
    
    environment {
        registry = "venus90210/sorteo_api"
        registryCredential = 'dockerhub'
    }
    
    tools {
    	maven 'Maven-3.8.6' 
  	}
  
    agent any 
    stages {
    
        stage('Source') {
            steps {
               
                sh 'mvn clean install'
            }
        }
        
        stage('Build') {
            steps {
                 sh 'docker build -t venus90210/sorteo_api:v1 .'
                  
            }
        }
        
        stage('Test') {
            steps {
                echo 'Hello world!' 
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Hello world!' 
            }
        }
    }
}